CREATE TABLE "survey_responses" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "survey_responses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userType" varchar(50) NOT NULL,
	"age" integer NOT NULL,
	"gender" varchar(50) NOT NULL,
	"weight" varchar(10) NOT NULL,
	"height" varchar(10) NOT NULL,
	"bmi" varchar(10) NOT NULL,
	"ultraProcessedFreq" varchar(50),
	"fruitsVegetablesFreq" varchar(50),
	"sweetsFreq" varchar(50),
	"mealsPerDay" varchar(10),
	"waterLitersPerDay" varchar(10),
	"physicalActivityHours" varchar(50),
	"smokingStatus" varchar(50),
	"alcoholFrequency" varchar(50),
	"sleepQuality" varchar(50),
	"bloodPressureMedication" varchar(50),
	"symptomFatigue" integer,
	"symptomWeightChange" integer,
	"symptomExcessiveThirst" integer,
	"symptomTemperatureSensitivity" integer,
	"symptomDrySkin" integer,
	"symptomMoodChanges" integer,
	"highBloodGlucoseHistory" varchar(50),
	"familyDiabetes" varchar(50),
	"familyThyroidIssues" varchar(50),
	"familyObesity" varchar(50),
	"findrisc_score" integer,
	"findrisc_risk_category" varchar(50),
	"submittedAt" timestamp DEFAULT now() NOT NULL,
	"ipAddress" varchar(45),
	"userAgent" text
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"openId" varchar(64) NOT NULL,
	"name" text,
	"email" varchar(320),
	"loginMethod" varchar(64),
	"role" "user_role" DEFAULT 'user' NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"lastSignedIn" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_openId_unique" UNIQUE("openId")
);
