CREATE TABLE `survey_responses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userType` varchar(50) NOT NULL,
	`age` int NOT NULL,
	`gender` varchar(50) NOT NULL,
	`weight` decimal(5,2) NOT NULL,
	`height` decimal(5,2) NOT NULL,
	`bmi` decimal(5,2) NOT NULL,
	`ultraProcessedFreq` varchar(50),
	`fruitsVegetablesFreq` varchar(50),
	`sweetsFreq` varchar(50),
	`mealsPerDay` int,
	`waterLitersPerDay` decimal(3,1),
	`physicalActivityHours` varchar(50),
	`smokingStatus` varchar(50),
	`alcoholFrequency` varchar(50),
	`sleepQuality` varchar(50),
	`bloodPressureMedication` varchar(50),
	`symptomFatigue` int,
	`symptomWeightChange` int,
	`symptomExcessiveThirst` int,
	`symptomTemperatureSensitivity` int,
	`symptomDrySkin` int,
	`symptomMoodChanges` int,
	`highBloodGlucoseHistory` varchar(50),
	`familyDiabetes` varchar(50),
	`familyThyroidIssues` varchar(50),
	`familyObesity` varchar(50),
	`findrisc_score` int,
	`findrisc_risk_category` varchar(50),
	`submittedAt` timestamp NOT NULL DEFAULT (now()),
	`ipAddress` varchar(45),
	`userAgent` text,
	CONSTRAINT `survey_responses_id` PRIMARY KEY(`id`)
);
